#spring:
#  datasource:
#    url: jdbc:h2:~/subway2;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: sa
#  sql:
#    init:
#      schema-locations: classpath*:schema.sql
#      mode: always

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
